### ISSUE TITLE
칸반에 todo, in progress, done 영역이 표시된다.

### ISSUE THREAD

**Issue by ingong** [boostcampwm-2021/WEB23-HyupUp#61]
- [ ] 칸반보드 UI 가 표시된다
- [ ] Todo Column 의 추가 버튼을 클릭하면 새로운 스토리가 state 에 추가된다
- [ ] 해당 컬럼의 최상단에 상태기반으로 UI 가 나타난다
